### ISSUE TITLE
Crashes on clone

### ISSUE THREAD

**Issue by walkero-gr** [sba1/simplegit#10]
When Itry to clone a git project from bitbucket.org the sgit crashes. Although that it creates the .git folder and a few files in there, it doesn't pull the project files. 

sgit v0.516

The system I run it is AmigaOS 4.1 Final Edition. I also have a crashlog at http://intercube.gr/Crashlog_git_2015-09-20_11-04-41.txt

**Comment by walkero-gr** [comment]
I test it with github.com and it seems that it works just fine with it. No crashes here.
I would like to use bitbucket instead of github. Is it possible to see a newer version of sgit supporting more git websites?

**Comment by ghost** [comment]
I think I ran into this with trying to make a checkout of linux kernel sources.

git on a raspberry pi (also 32bit) showed me the same issue,  yet running it on an ssh shell using a 64bit machine let me complete the cloning.

There seems to be some non-codebase minor differences between builds even when linux native.

**Comment by walkero-gr** [comment]
Are there any news on that? is there going to be any updates to sgit, even with the latest version of libgit2? it might fixes this problem.
Thank you for your time.

**Comment by ghost** [comment]
5No idea,  I've only managed to make a working cross-compiler setup using a debianized system and the same build was incapable of working on gentoo or arch Linux hosts.

I'm going to be preparing a Linux machine sometime within the next year and see what I can do about the whole autotools mess that is the existing adtools development setup.

I've run into multiple things requiring more stable and up to date development tools natively instead of the arcane deep black arts of cross compilation that seems to have become the prerequisite of building any modern amigaos applications of any kind.

**Comment by sba1** [comment]
> Are there any news on that? is there going to be any updates to sgit,
> even with the latest version of libgit2? it might fixes this problem.
> Thank you for your time.

I will have some time after christmas and I'm going to look at it then.

**Comment by sba1** [comment]
Should be fixed now.

**Comment by raziel-** [comment]
I checked out a test source from bitbucket...works fine with 535

**Comment by sba1** [comment]
Closing this as well.

**Comment by walkero-gr** [comment]
worked fine for me too... Thanks
